//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldCupWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorldCupWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Details.
        /// </summary>
        public static string btnMatchDetails {
            get {
                return ResourceManager.GetString("btnMatchDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to match.
        /// </summary>
        public static string btnReturnToMatch {
            get {
                return ResourceManager.GetString("btnReturnToMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string btnSettings {
            get {
                return ResourceManager.GetString("btnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Match.
        /// </summary>
        public static string lblChooseMatch {
            get {
                return ResourceManager.GetString("lblChooseMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draws:.
        /// </summary>
        public static string lblDraws {
            get {
                return ResourceManager.GetString("lblDraws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Settings.
        /// </summary>
        public static string lblEditSettings {
            get {
                return ResourceManager.GetString("lblEditSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal difference:.
        /// </summary>
        public static string lblGoalsDiff {
            get {
                return ResourceManager.GetString("lblGoalsDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals scored:.
        /// </summary>
        public static string lblGoalsScored {
            get {
                return ResourceManager.GetString("lblGoalsScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals taken:.
        /// </summary>
        public static string lblGoalsTaken {
            get {
                return ResourceManager.GetString("lblGoalsTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League:.
        /// </summary>
        public static string lblLeague {
            get {
                return ResourceManager.GetString("lblLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losses:.
        /// </summary>
        public static string lblLosses {
            get {
                return ResourceManager.GetString("lblLosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution:.
        /// </summary>
        public static string lblResolution {
            get {
                return ResourceManager.GetString("lblResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Statistics.
        /// </summary>
        public static string lblStatistics {
            get {
                return ResourceManager.GetString("lblStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins:.
        /// </summary>
        public static string lblWins {
            get {
                return ResourceManager.GetString("lblWins", resourceCulture);
            }
        }
    }
}
