// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do one of these:
//
//    using DAL.Models;
//
//    var groupResults = GroupResults.FromJson(jsonString);
//    var matches = Matches.FromJson(jsonString);
//    var results = Results.FromJson(jsonString);
//    var teams = Teams.FromJson(jsonString);
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8603

namespace DAL.Models
{
    using DAL.Models.Converters;
    using System.Collections.Generic;
    using System.Text.Json;

    //public partial class GroupResults
    //{
    //    public static List<GroupResults> FromJson(string json) => JsonSerializer.Deserialize<List<GroupResults>>(json, Converter.Settings);
    //}

    //public partial class Matches
    //{
    //    public static List<Matches> FromJson(string json) => JsonSerializer.Deserialize<List<Matches>>(json, Converter.Settings);
    //}

    //public partial class Results
    //{
    //    public static List<Results> FromJson(string json) => JsonSerializer.Deserialize<List<Results>>(json, Converter.Settings);
    //}

    //public partial class Teams
    //{

    //}
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8603
